logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

server:
  port: 8040

turbine:
  stream:
    port: 8041

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/

spring:
  rabbitmq:
    host: 101.132.174.159
    port: 5672
    username: admin
    password: admin
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://monitor:${turbine.stream.port}

security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}